### ISSUE TITLE
Compiling with `-install_path` and `-rpath` flags containing `@` macros fails

### ISSUE THREAD

**Issue by rrbutani** [bazel-contrib/toolchains_llvm#135]
H/t to @vinistock for finding [this issue](https://github.com/grailbio/bazel-toolchain/issues/88#issuecomment-1021579070).

The below is mostly copied from #88; the issue is essentially that we're parsing `-install_path @executable_path/...` and similar flags as param files, incorrectly.

-----

> [That snippet](https://github.com/grailbio/bazel-toolchain/blob/619f31df5e1fd1f769c406012963f9655ae31adf/toolchain/osx_cc_wrapper.sh.tpl#L53-L63) was added to support [parameter files](https://stackoverflow.com/questions/7139685/does-gcc-support-command-files).
> 
> The macOS cc wrapper script inspects the full command line in order to remap libraries that are being linked against to their fully resolved paths, taking into account the [`rpath`](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/RunpathDependentLibraries.html)s added to the binary. I don't have first-hand experience with this but this is [allegedly](https://github.com/bazelbuild/bazel/blob/6b32f227f21c9a9e5dbff713ac1ba3f662b47007/tools/cpp/osx_cc_wrapper.sh#L17-L23) because of some [oddness](https://stackoverflow.com/questions/39601359/osx-gcc-clang-how-to-set-a-dynamic-non-standard-library-framework-path-wit) having to do with runpaths added to binaries ([this](https://github.com/bazelbuild/bazel/commit/28ac615402bfbba56fbcbc6b4f3f51fca8bc9612) has some context; I _think_ it's that the paths are relative to the build dir and not the workspace that's causing the issue but I have no idea what's introducing the `-Wl,-rpath`s in the first place).
> 
> Anyways, for that reason we need to actually read what's in the parameter file. The PR in this repo you linked to was essentially copied from upstream ([this commit](https://github.com/bazelbuild/bazel/commit/f08819b731f8bb5d95c196c2781e54908b846b74)); in general the logic in the macOS wrapper mostly comes from upstream.
> 
> The issue here, of course, is that the `@` in `-install_name @execution_path/...` does _not_ signify a parameter file!
> 
> What's peculiar to me is that upstream Bazel seems to fail on this in the exact same way ([here's a minimal test case](https://gist.github.com/rrbutani/a0a52776d87b026ef1339445070353fd)). Perhaps it's simply not common for users to want to generate dylibs with `install_path`s from Bazel and it hasn't come up? Not sure.

----

Extending the logic in the macOS wrapper to skip processing args starting with `@` (like `@execution_path/...`, `@executable_path/...`, `@load_path/..`, `@rpath/...`, etc.) when the preceeding arg is `-install_name` or `-rpath` is the obvious fix, I think.

I have a few concerns though:
  - is this genuinely an error with the default Bazel toolchain?
    + edit: it appears so: bazelbuild/bazel#13044
  - are `-install_name` and `-rpath` the only args that accept `@` macro form args? might be worth checking the `clang` arg parsing source to be sure
    + edit: it's probably better to just check that the file exists instead of maintaining a list. FWIW clang and the linker don't seem to actually even have a list of `@` macros that are acceptable; passing in `@some_random_thing` will compile successfully. grepping through [`dyld` source](https://opensource.apple.com/source/dyld/) and peering through the `dyld` man pages does indicate that it's really just `@rpath`, `@executable_path`, and `@loader_path` though. (`@execution_path` seems to be just a typo that a few people independently made over the years)
  - what kind of path remapping should we be doing for `-install_name` and `-rpath`?
    + I think the answer is "none" for `-install_name` but what about `-rpath`? Don't we have the same issues as with `-Wl,-rpath`? `-rpath` certainly does seem to just expand out into `-rpath` to the linker, experimentally. Are we just banking on users always using the not-macOS-specific `-Wl` form?
      * edit: going to add `-rpath @loader_path/...` to `$RPATHS` too; this misses `-Xlinker -rpath -Xlinker @loader_path/...` but I think that's okay for now.
  - why does the logic in the wrapper only check for `@loader_path`?
    + edit: not really sure but assuming this is the path of the directory the `dylib` being loaded was found at at link time it makes sense that this doesn't match up with the runtime search path, for Bazel. if you don't think about it too hard.

**Comment by vinistock** [comment]
For your reference, the flag is added by Ruby's `configure` script. As instructed by the [README](https://github.com/ruby/ruby#how-to-compile-and-install), running `autogen.sh` creates the `configure` script, which in turn adds the `install_name` flag.

Although the `configure` script itself doesn't exist in the repository (since it's autogenerated), we can see the relevant lines in `configure.ac`. [Here is where it sets the install_name](https://github.com/ruby/ruby/blob/bffd6cbd97dd61e347a8f7de36266809444fb4c1/configure.ac#L3550) and a few lines above is [where the base path is set](https://github.com/ruby/ruby/blob/bffd6cbd97dd61e347a8f7de36266809444fb4c1/configure.ac#L3547).

Sorbet's custom build does the same process, integrating it with Bazel. [Here is where configure is invoked and install_name is set](https://github.com/sorbet/sorbet/blob/a0c88fe9ce2ce713a1e0b386460704284d50c568/third_party/ruby/build-ruby.bzl#L100) and the build fails immediately after [when compiling](https://github.com/sorbet/sorbet/blob/a0c88fe9ce2ce713a1e0b386460704284d50c568/third_party/ruby/build-ruby.bzl#L109) (because `cc_wrapper` will try to read the path).

In respect to your concerns, I'll need to do more research to be of more help. But I can confirm that changing the `cc_wrapper` to not do any special processing of arguments beginning with `@` makes the build succeed. For example, swapping the loop that parses arguments for this does the trick
```bash
for i in "$@"; do
    parse_option "$i"
done
```

**Comment by rrbutani** [comment]
> In respect to your concerns, I'll need to do more research to be of more help.

Whoops my bad, I wasn't expecting you to try to find the answers to those questions; just thinking out loud.

> Sorbet's custom build does the same process, integrating it with Bazel. [Here is where configure is invoked and install_name is set](https://github.com/sorbet/sorbet/blob/a0c88fe9ce2ce713a1e0b386460704284d50c568/third_party/ruby/build-ruby.bzl#L100) and the build fails immediately after [when compiling](https://github.com/sorbet/sorbet/blob/a0c88fe9ce2ce713a1e0b386460704284d50c568/third_party/ruby/build-ruby.bzl#L109) (because `cc_wrapper` will try to read the path).

Got it, thanks.

**Comment by keith** [comment]
Note I believe this case should be fixed once https://github.com/bazelbuild/bazel/pull/13148 lands

**Comment by rrbutani** [comment]
> Note I believe this case should be fixed once [bazelbuild/bazel#13148](https://github.com/bazelbuild/bazel/pull/13148) lands

Thank you. And thanks for bumping that PR/writing bazelbuild/bazel#14650.

**Comment by garymm** [comment]
I think the referenced bazel fixes are in bazel 6.0.0 but I'm still seeing failures when using @rrbutani's test case from the gist.
Tried on `6.0.0` and `7.0.0-pre.20221212.2`.

Any idea what's needed?

**Comment by siddharthab** [comment]
This may be resolved now with the new wrapper scripts. Can someone please try it and close this issue?

**Comment by siddharthab** [comment]
Closing now, but can reopen if someone says something.

**Comment by ashi009** [comment]
Please reopen. Just tried 1.2.0, still having this issue with `-install_name @rpath/libomp.dylib`

**Comment by ashi009** [comment]
It also incorrectly intercepts `@loader_path` from `-Xlinker -rpath -Xlinker @loader_path/blah` and leaves a dangling `-Xlinker` flag in the command line for clang:

> clang: error: argument to '-Xlinker' is missing (expected 1 value)
